spring:
  datasource:
    url: jdbc:mysql://localhost:3306/musica
    username: dani
    password: ih84zYyrcR]bdoe0
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true


  application:
    name: APICDS

  server:
    port: 0

  eureka:
    instance:
      prefer-ip-address: true
    client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka
