spring:

  application:
    name: APICDS

  datasource:
    url: jdbc:mysql://localhost:3306/musica
    username: dani
    password: ih84zYyrcR]bdoe0
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  eureka:
    instance:
      prefer-ip-address: true
    client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka

  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui-custom.html

server:
  port: 0

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

dolarapi:
  url: https://dolarapi.com/v1/dolares
  connection-timeout: 5000
  read-timeout: 5000